### ISSUE TITLE
No Module Named scipy.fft

### ISSUE THREAD

**Issue by rudrathegreat** [davidpraise45/Audio-Signal-Processing#1]
Hi,

I was experimenting with this code when I came across this error saying- 

```Python

Traceback (most recent call last):
  File "D:/filename.py", line 41, in <module>
    import scipy.fft
ModuleNotFoundError: No module named 'scipy.fft'

```

I do have SciPy, NumPy and Matplotlib, but yet the error keeps showing!

### Requirements.txt

```

matplotlib==2.2.2
numpy==1.15.0
pandas==0.23.4
Pillow==5.2.0
PyAudio==0.2.11
scipy==1.1.0

```
A little help would be great!

**Comment by rudrathegreat** [comment]
I have found something.

When I am using my IDE editor (PyCharm), I get the error, but when I use Python IDLE, I don't

**Comment by davidpraise45** [comment]
Hey, have you tried sudo pip install scipy on your computer, or if your have anaconda installed on your pc you don't have to install it ?

**Comment by rudrathegreat** [comment]
I don't have the anaconda distribution. However, when I want to check if I have installed some open-source library, like scipy, I simply just try to import it in the Python Shell. If that works, then you know that library has been installed. When I do that with scipy, I find that there is no error, meaning that it is installed.

**Comment by davidpraise45** [comment]
> I have found something.
> 
> When I am using my IDE editor (PyCharm), I get the error, but when I use Python IDLE, I don't

It must be your setup environment with pycharm, go to setting on pycharm and python interpreter and choose the correct interpreter.

**Comment by rudrathegreat** [comment]
I've already done that, still gives the error!

**Comment by davidpraise45** [comment]
My best option is to install anaconda, and use that environment. So you can
use it in pycharm and idle.

**Comment by rudrathegreat** [comment]
I have finally found out what the problem is!!!!!!!!

But in order to make sure that this is true, I need to ask you a question.

In the line - 

```Python

from scipy import fft

```

Are you really try to import this - 

```Python

from scipy.fftpack import fft

```

If that is the case, then change the import statement `from scipy import fft` to `from scipy.fftpack import fft`

**Comment by davidpraise45** [comment]
That's what exactly what I imported fast Fourier transformation (fft)

D.k

**Comment by rudrathegreat** [comment]
Cool bananas!!!

P.S - I do not really understand what D.k means... um... explanation

**Comment by hafez-ahmad** [comment]
this worked for me.
from scipy import fft
from scipy import ifft

**Comment by rudrathegreat** [comment]
that was what was in the code. Scipy updated it to -

```Python

from scipy.fftpack import fft

```

**Comment by WarrenWeckesser** [comment]
FYI: The module `scipy.fft` was added in version 1.4.0 of SciPy.  It is a replacement for the older `scipy.fftpack`.
